/**
 * AcademicFlow's figure library, snapshotted so the prompt builder and the figure-id
 * validator stay pure and network-free. Regenerate with `npm run sync:figures` against
 * a running flow-app render server — do not hand-edit.
 *
 * `en` is derived from the id (the ids are English words behind a category prefix), so
 * it can never drift from the identifier the model has to emit. `tr` is AcademicFlow's
 * own display name.
 *
 * Generated from http://127.0.0.1:8787/v1/figures — 205 figures, 20 categories.
 */

export interface FlowFigure {
  id: string;
  category: string;
  /** English gloss derived from the id — what an English prompt searches on. */
  en: string;
  /** AcademicFlow's Turkish display name. */
  tr: string;
}

export const FLOW_FIGURE_CATEGORIES = [
  'Abstract',
  'Analytics',
  'Anatomy',
  'Cardiology',
  'CellBio',
  'Charts',
  'Connectors',
  'Devices',
  'Evidence',
  'Geo',
  'Health',
  'Imaging',
  'Lab',
  'Metrics',
  'Molecular',
  'Organisms',
  'People',
  'Realistic',
  'Research',
  'Science',
] as const;

export type FlowFigureCategory = (typeof FLOW_FIGURE_CATEGORIES)[number];

export const FLOW_FIGURES: readonly FlowFigure[] = [
  { id: 'sf-arrow-down', category: 'Abstract', en: "arrow down", tr: "Arrow Down" },
  { id: 'sf-arrow-right', category: 'Abstract', en: "arrow right", tr: "Arrow Right" },
  { id: 'sf-decrease', category: 'Abstract', en: "decrease", tr: "Decrease" },
  { id: 'sf-increase', category: 'Abstract', en: "increase", tr: "Increase" },
  { id: 'sf-plus', category: 'Abstract', en: "plus", tr: "Plus" },
  { id: 'sf-significance', category: 'Abstract', en: "significance", tr: "Significance" },
  { id: 'sf-vs-badge', category: 'Abstract', en: "vs badge", tr: "VS Badge" },
  { id: 'atom-mind', category: 'Analytics', en: "atom mind", tr: "Atom ve Zihin" },
  { id: 'axes', category: 'Analytics', en: "axes", tr: "Eksenler" },
  { id: 'bell-curve', category: 'Analytics', en: "bell curve", tr: "Çan Eğrisi" },
  { id: 'brain-idea', category: 'Analytics', en: "brain idea", tr: "Beyin ve Fikir" },
  { id: 'database', category: 'Analytics', en: "database", tr: "Veritabanı" },
  { id: 'dice', category: 'Analytics', en: "dice", tr: "Zar" },
  { id: 'eye', category: 'Analytics', en: "eye", tr: "Göz" },
  { id: 'funnel', category: 'Analytics', en: "funnel", tr: "Huni" },
  { id: 'gauge', category: 'Analytics', en: "gauge", tr: "Gösterge" },
  { id: 'heatmap', category: 'Analytics', en: "heatmap", tr: "Isı Haritası" },
  { id: 'hourglass', category: 'Analytics', en: "hourglass", tr: "Kum Saati" },
  { id: 'lightbulb', category: 'Analytics', en: "lightbulb", tr: "Ampul" },
  { id: 'magnifier', category: 'Analytics', en: "magnifier", tr: "Büyüteç" },
  { id: 'presentation', category: 'Analytics', en: "presentation", tr: "Sunum" },
  { id: 'settings-gear', category: 'Analytics', en: "settings gear", tr: "Ayarlar" },
  { id: 'stopwatch', category: 'Analytics', en: "stopwatch", tr: "Kronometre" },
  { id: 'strategy-chess', category: 'Analytics', en: "strategy chess", tr: "Strateji" },
  { id: 'target', category: 'Analytics', en: "target", tr: "Hedef" },
  { id: 'thought-bubble', category: 'Analytics', en: "thought bubble", tr: "Düşünce Balonu" },
  { id: 'trend-up', category: 'Analytics', en: "trend up", tr: "Yükselen Trend" },
  { id: 'venn', category: 'Analytics', en: "venn", tr: "Venn Şeması" },
  { id: 'artery', category: 'Anatomy', en: "artery", tr: "Damar" },
  { id: 'bone', category: 'Anatomy', en: "bone", tr: "Kemik" },
  { id: 'cell', category: 'Anatomy', en: "cell", tr: "Hücre" },
  { id: 'fl-brain', category: 'Anatomy', en: "brain", tr: "Beyin (Fluent)" },
  { id: 'fl-eye', category: 'Anatomy', en: "eye", tr: "Göz (Fluent)" },
  { id: 'fl-heart', category: 'Anatomy', en: "heart", tr: "Kalp (Fluent)" },
  { id: 'hi-ambulance', category: 'Anatomy', en: "ambulance", tr: "Ambulans" },
  { id: 'hi-blood-cells', category: 'Anatomy', en: "blood cells", tr: "Kan Hücresi" },
  { id: 'hi-blood-pressure', category: 'Anatomy', en: "blood pressure", tr: "Tansiyon" },
  { id: 'hi-brain', category: 'Anatomy', en: "brain", tr: "Beyin" },
  { id: 'hi-eye', category: 'Anatomy', en: "eye", tr: "Göz" },
  { id: 'hi-heart', category: 'Anatomy', en: "heart", tr: "Kalp" },
  { id: 'hi-joints', category: 'Anatomy', en: "joints", tr: "Eklem" },
  { id: 'hi-kidneys', category: 'Anatomy', en: "kidneys", tr: "Böbrek" },
  { id: 'hi-liver', category: 'Anatomy', en: "liver", tr: "Karaciğer" },
  { id: 'hi-lungs', category: 'Anatomy', en: "lungs", tr: "Akciğer" },
  { id: 'hi-stethoscope', category: 'Anatomy', en: "stethoscope", tr: "Stetoskop" },
  { id: 'hi-thermometer', category: 'Anatomy', en: "thermometer", tr: "Termometre" },
  { id: 'hi-tooth', category: 'Anatomy', en: "tooth", tr: "Diş" },
  { id: 'ph-bone', category: 'Anatomy', en: "bone", tr: "Kemik" },
  { id: 'ph-pulse', category: 'Anatomy', en: "pulse", tr: "Nabız" },
  { id: 'ph-stethoscope', category: 'Anatomy', en: "stethoscope", tr: "Stetoskop" },
  { id: 'sf-cell', category: 'Anatomy', en: "cell", tr: "Cell" },
  { id: 'sf-erythrocyte', category: 'Anatomy', en: "erythrocyte", tr: "Erythrocyte" },
  { id: 'sf-neuron', category: 'Anatomy', en: "neuron", tr: "Neuron" },
  { id: 'sf-platelet', category: 'Anatomy', en: "platelet", tr: "Platelet" },
  { id: 'sf-spine', category: 'Anatomy', en: "spine", tr: "Spine" },
  { id: 'sf-stomach', category: 'Anatomy', en: "stomach", tr: "Stomach" },
  { id: 'sf-thyroid', category: 'Anatomy', en: "thyroid", tr: "Thyroid" },
  { id: 'sf-aneurysm', category: 'Cardiology', en: "aneurysm", tr: "Aneurysm" },
  { id: 'sf-aorta', category: 'Cardiology', en: "aorta", tr: "Aorta" },
  { id: 'sf-atherosclerosis', category: 'Cardiology', en: "atherosclerosis", tr: "Atherosclerosis" },
  { id: 'sf-blood-pressure', category: 'Cardiology', en: "blood pressure", tr: "Blood Pressure" },
  { id: 'sf-cabg', category: 'Cardiology', en: "cabg", tr: "CABG" },
  { id: 'sf-capillary-bed', category: 'Cardiology', en: "capillary bed", tr: "Capillary Bed" },
  { id: 'sf-cardiac-valve', category: 'Cardiology', en: "cardiac valve", tr: "Cardiac Valve" },
  { id: 'sf-cardiomyocyte', category: 'Cardiology', en: "cardiomyocyte", tr: "Cardiomyocyte" },
  { id: 'sf-carotid-bifurcation', category: 'Cardiology', en: "carotid bifurcation", tr: "Carotid Bifurcation" },
  { id: 'sf-catheterization', category: 'Cardiology', en: "catheterization", tr: "Catheterization" },
  { id: 'sf-conduction-system', category: 'Cardiology', en: "conduction system", tr: "Conduction System" },
  { id: 'sf-coronary-arteries', category: 'Cardiology', en: "coronary arteries", tr: "Coronary Arteries" },
  { id: 'sf-coronary-stent', category: 'Cardiology', en: "coronary stent", tr: "Coronary Stent" },
  { id: 'sf-ecg-ekg', category: 'Cardiology', en: "ecg ekg", tr: "ECG / EKG" },
  { id: 'sf-mitral-valve', category: 'Cardiology', en: "mitral valve", tr: "Mitral Valve" },
  { id: 'sf-pacemaker', category: 'Cardiology', en: "pacemaker", tr: "Pacemaker" },
  { id: 'sf-pericardium', category: 'Cardiology', en: "pericardium", tr: "Pericardium" },
  { id: 'sf-venous-valve', category: 'Cardiology', en: "venous valve", tr: "Venous Valve" },
  { id: 'ga-b-cell', category: 'CellBio', en: "b cell", tr: "B Cell" },
  { id: 'ga-macrophage', category: 'CellBio', en: "macrophage", tr: "Macrophage" },
  { id: 'ga-t-cell', category: 'CellBio', en: "t cell", tr: "T Cell" },
  { id: 'ga-tumor', category: 'CellBio', en: "tumor", tr: "Tumor" },
  { id: 'barchart', category: 'Charts', en: "barchart", tr: "Bar" },
  { id: 'linechart', category: 'Charts', en: "linechart", tr: "Çizgi" },
  { id: 'piechart', category: 'Charts', en: "piechart", tr: "Pasta" },
  { id: 'scatter', category: 'Charts', en: "scatter", tr: "Saçılım" },
  { id: 'sf-bar-chart', category: 'Charts', en: "bar chart", tr: "Bar Chart" },
  { id: 'sf-box-plot', category: 'Charts', en: "box plot", tr: "Box Plot" },
  { id: 'sf-forest-plot', category: 'Charts', en: "forest plot", tr: "Forest Plot" },
  { id: 'sf-funnel-plot', category: 'Charts', en: "funnel plot", tr: "Funnel Plot" },
  { id: 'sf-histogram', category: 'Charts', en: "histogram", tr: "Histogram" },
  { id: 'sf-roc-curve', category: 'Charts', en: "roc curve", tr: "ROC Curve" },
  { id: 'sf-scatter-plot', category: 'Charts', en: "scatter plot", tr: "Scatter Plot" },
  { id: 'table', category: 'Charts', en: "table", tr: "Tablo" },
  { id: 'ga-activate', category: 'Connectors', en: "activate", tr: "Activation" },
  { id: 'ga-bidirectional', category: 'Connectors', en: "bidirectional", tr: "Bidirectional Arrow" },
  { id: 'ga-bracket-left', category: 'Connectors', en: "bracket left", tr: "Bracket Left" },
  { id: 'ga-bracket-right', category: 'Connectors', en: "bracket right", tr: "Bracket Right" },
  { id: 'ga-curved-arrow', category: 'Connectors', en: "curved arrow", tr: "Curved Arrow" },
  { id: 'ga-cycle', category: 'Connectors', en: "cycle", tr: "Cycle Arrow" },
  { id: 'ga-inhibit', category: 'Connectors', en: "inhibit", tr: "Inhibition" },
  { id: 'dv-bp-cuff-arm', category: 'Devices', en: "bp cuff arm", tr: "BP Cuff on Arm" },
  { id: 'dv-bp-monitor', category: 'Devices', en: "bp monitor", tr: "Blood Pressure Monitor" },
  { id: 'dv-dialysis', category: 'Devices', en: "dialysis", tr: "Dialysis Machine" },
  { id: 'dv-ecg-monitor', category: 'Devices', en: "ecg monitor", tr: "ECG Monitor" },
  { id: 'dv-hospital-bed', category: 'Devices', en: "hospital bed", tr: "Hospital Bed" },
  { id: 'dv-infusion-pump', category: 'Devices', en: "infusion pump", tr: "Infusion Pump" },
  { id: 'dv-iv-bag', category: 'Devices', en: "iv bag", tr: "IV Infusion Bag" },
  { id: 'dv-oxygen-mask', category: 'Devices', en: "oxygen mask", tr: "Oxygen Mask" },
  { id: 'dv-stethoscope', category: 'Devices', en: "stethoscope", tr: "Stethoscope (flat)" },
  { id: 'dv-syringe', category: 'Devices', en: "syringe", tr: "Syringe" },
  { id: 'ev-balance-scales', category: 'Evidence', en: "balance scales", tr: "Balance Scales" },
  { id: 'ev-checklist', category: 'Evidence', en: "checklist", tr: "Checklist" },
  { id: 'ev-database-search', category: 'Evidence', en: "database search", tr: "Literature Database Search" },
  { id: 'ev-forest-plot', category: 'Evidence', en: "forest plot", tr: "Forest Plot" },
  { id: 'ev-funnel-plot', category: 'Evidence', en: "funnel plot", tr: "Funnel Plot" },
  { id: 'ev-grade-shield', category: 'Evidence', en: "grade shield", tr: "Certainty Shield (GRADE)" },
  { id: 'ev-meta-diamond', category: 'Evidence', en: "meta diamond", tr: "Meta-analysis Summary" },
  { id: 'ev-prisma-clipboard', category: 'Evidence', en: "prisma clipboard", tr: "Study Protocol Clipboard" },
  { id: 'ev-registry', category: 'Evidence', en: "registry", tr: "Trial Registry Record" },
  { id: 'ev-risk-of-bias', category: 'Evidence', en: "risk of bias", tr: "Risk of Bias Grid" },
  { id: 'gg-globe', category: 'Geo', en: "globe", tr: "Globe" },
  { id: 'gg-hospital', category: 'Geo', en: "hospital", tr: "Hospital Building" },
  { id: 'gg-map-pin', category: 'Geo', en: "map pin", tr: "Location Pin" },
  { id: 'gg-metro', category: 'Geo', en: "metro", tr: "Metropolitan" },
  { id: 'gg-rural', category: 'Geo', en: "rural", tr: "Rural / Non-metropolitan" },
  { id: 'gg-us-map', category: 'Geo', en: "us map", tr: "United States Map" },
  { id: 'gg-us-map-regions', category: 'Geo', en: "us map regions", tr: "USA by Region" },
  { id: 'apple', category: 'Health', en: "apple", tr: "Sağlıklı Beslenme" },
  { id: 'blood-pressure', category: 'Health', en: "blood pressure", tr: "Tansiyon" },
  { id: 'crutches', category: 'Health', en: "crutches", tr: "Koltuk Değneği" },
  { id: 'doctor', category: 'Health', en: "doctor", tr: "Doktor" },
  { id: 'heartbeat', category: 'Health', en: "heartbeat", tr: "EKG" },
  { id: 'hospital-bed', category: 'Health', en: "hospital bed", tr: "Hasta Yatağı" },
  { id: 'iv-bag', category: 'Health', en: "iv bag", tr: "Serum" },
  { id: 'medical-cross', category: 'Health', en: "medical cross", tr: "Sağlık Çaprazı" },
  { id: 'mental-health', category: 'Health', en: "mental health", tr: "Zihin Sağlığı" },
  { id: 'running', category: 'Health', en: "running", tr: "Koşu" },
  { id: 'scale', category: 'Health', en: "scale", tr: "Baskül" },
  { id: 'stethoscope', category: 'Health', en: "stethoscope", tr: "Stetoskop" },
  { id: 'syringe', category: 'Health', en: "syringe", tr: "Şırınga" },
  { id: 'toothbrush', category: 'Health', en: "toothbrush", tr: "Diş Fırçası" },
  { id: 'yoga', category: 'Health', en: "yoga", tr: "Yoga" },
  { id: 'ga-ct-scan', category: 'Imaging', en: "ct scan", tr: "CT / MRI" },
  { id: 'ga-ultrasound', category: 'Imaging', en: "ultrasound", tr: "Ultrasound" },
  { id: 'ga-xray', category: 'Imaging', en: "xray", tr: "X-Ray" },
  { id: 'ga-beaker', category: 'Lab', en: "beaker", tr: "Beaker" },
  { id: 'ga-centrifuge', category: 'Lab', en: "centrifuge", tr: "Centrifuge" },
  { id: 'ga-elisa', category: 'Lab', en: "elisa", tr: "ELISA Plate" },
  { id: 'ga-flow-cytometry', category: 'Lab', en: "flow cytometry", tr: "Flow Cytometry" },
  { id: 'ga-gel', category: 'Lab', en: "gel", tr: "Gel Electrophoresis" },
  { id: 'ga-pcr', category: 'Lab', en: "pcr", tr: "PCR Machine" },
  { id: 'ga-petri-dish', category: 'Lab', en: "petri dish", tr: "Petri Dish" },
  { id: 'ga-pipette', category: 'Lab', en: "pipette", tr: "Pipette" },
  { id: 'ga-western-blot', category: 'Lab', en: "western blot", tr: "Western Blot" },
  { id: 'mt-calendar', category: 'Metrics', en: "calendar", tr: "Study Period" },
  { id: 'mt-clock', category: 'Metrics', en: "clock", tr: "Time to Event" },
  { id: 'mt-donut-gauge', category: 'Metrics', en: "donut gauge", tr: "Donut Gauge" },
  { id: 'mt-mortality-arrow', category: 'Metrics', en: "mortality arrow", tr: "Mortality Reduction" },
  { id: 'mt-percent', category: 'Metrics', en: "percent", tr: "Percentage Badge" },
  { id: 'mt-stat-bars', category: 'Metrics', en: "stat bars", tr: "Statistics Bars" },
  { id: 'mt-target', category: 'Metrics', en: "target", tr: "Target" },
  { id: 'mt-trend-down', category: 'Metrics', en: "trend down", tr: "Falling Trend" },
  { id: 'mt-trend-up', category: 'Metrics', en: "trend up", tr: "Rising Trend" },
  { id: 'ga-antibody', category: 'Molecular', en: "antibody", tr: "Antibody" },
  { id: 'ga-dna-helix', category: 'Molecular', en: "dna helix", tr: "DNA Helix" },
  { id: 'ga-pathway', category: 'Molecular', en: "pathway", tr: "Signaling Pathway" },
  { id: 'ga-protein', category: 'Molecular', en: "protein", tr: "Protein" },
  { id: 'ga-receptor', category: 'Molecular', en: "receptor", tr: "Receptor" },
  { id: 'ga-rna', category: 'Molecular', en: "rna", tr: "mRNA" },
  { id: 'ga-bacteria', category: 'Organisms', en: "bacteria", tr: "Bacteria" },
  { id: 'ga-cohort', category: 'Organisms', en: "cohort", tr: "Patient Cohort" },
  { id: 'ga-human', category: 'Organisms', en: "human", tr: "Human Figure" },
  { id: 'ga-mouse', category: 'Organisms', en: "mouse", tr: "Lab Mouse" },
  { id: 'ga-rat', category: 'Organisms', en: "rat", tr: "Lab Rat" },
  { id: 'ga-zebrafish', category: 'Organisms', en: "zebrafish", tr: "Zebrafish" },
  { id: 'pp-caring-hands', category: 'People', en: "caring hands", tr: "Caring Hands" },
  { id: 'pp-doctor', category: 'People', en: "doctor", tr: "Clinician" },
  { id: 'pp-elderly-couple', category: 'People', en: "elderly couple", tr: "Elderly Couple" },
  { id: 'pp-group3', category: 'People', en: "group3", tr: "Group of Three" },
  { id: 'pp-man', category: 'People', en: "man", tr: "Man" },
  { id: 'pp-patient-bed', category: 'People', en: "patient bed", tr: "Patient in Bed" },
  { id: 'pp-person', category: 'People', en: "person", tr: "Adult" },
  { id: 'pp-population', category: 'People', en: "population", tr: "Population Grid" },
  { id: 'pp-woman', category: 'People', en: "woman", tr: "Woman" },
  { id: 'sd-brain', category: 'Realistic', en: "brain", tr: "Beyin (Gerçekçi)" },
  { id: 'sd-heart', category: 'Realistic', en: "heart", tr: "Kalp (Gerçekçi)" },
  { id: 'sd-lungs', category: 'Realistic', en: "lungs", tr: "Akciğer (Gerçekçi)" },
  { id: 'sd-mouse', category: 'Realistic', en: "mouse", tr: "Fare" },
  { id: 'ga-p-value', category: 'Research', en: "p value", tr: "P-value Star" },
  { id: 'ga-randomize', category: 'Research', en: "randomize", tr: "Randomization" },
  { id: 'ga-sample', category: 'Research', en: "sample", tr: "Sample Collection" },
  { id: 'ga-timeline', category: 'Research', en: "timeline", tr: "Timeline" },
  { id: 'hi-dna', category: 'Science', en: "dna", tr: "DNA" },
  { id: 'hi-microscope', category: 'Science', en: "microscope", tr: "Mikroskop" },
  { id: 'hi-pill-1', category: 'Science', en: "pill 1", tr: "Hap" },
  { id: 'hi-syringe', category: 'Science', en: "syringe", tr: "Şırınga" },
  { id: 'hi-virus', category: 'Science', en: "virus", tr: "Virüs" },
  { id: 'molecule', category: 'Science', en: "molecule", tr: "Molekül" },
  { id: 'ph-atom', category: 'Science', en: "atom", tr: "Atom" },
  { id: 'ph-bug', category: 'Science', en: "bug", tr: "Mikrop" },
  { id: 'ph-first-aid', category: 'Science', en: "first aid", tr: "İlk Yardım" },
  { id: 'ph-flask', category: 'Science', en: "flask", tr: "Kolonya Şişesi" },
  { id: 'ph-microscope', category: 'Science', en: "microscope", tr: "Mikroskop" },
  { id: 'ph-pill', category: 'Science', en: "pill", tr: "Hap" },
  { id: 'ph-syringe', category: 'Science', en: "syringe", tr: "Şırınga" },
  { id: 'ph-test-tube', category: 'Science', en: "test tube", tr: "Test Tüpü" },
  { id: 'ph-virus', category: 'Science', en: "virus", tr: "Virüs" },
];

const BY_ID = new Map(FLOW_FIGURES.map((f) => [f.id, f]));

/**
 * Whether a figure id exists. AcademicFlow drops unknown ids silently while rendering,
 * so a spec full of invented icons comes back as text-only panels with no error — this
 * is the only place that catches it.
 */
export function hasFigure(id: string): boolean {
  return BY_ID.has(id);
}

export function getFigure(id: string): FlowFigure | undefined {
  return BY_ID.get(id);
}

/** Figures in the given categories, or all of them when no filter is given. */
export function figuresIn(categories?: readonly string[]): readonly FlowFigure[] {
  if (!categories || categories.length === 0) return FLOW_FIGURES;
  const wanted = new Set(categories);
  return FLOW_FIGURES.filter((f) => wanted.has(f.category));
}
