import type { Ref } from '@/store/types';
import { buildCitationKeyMap, generateBibtex } from '@/lib/refs/bibtex-out';
import { isNumericStyle, type CitationStyle, type StyleId } from '@/lib/refs/styles';
import {
  collectFigureLegends,
  type FigureCaptionPlacement,
} from '@/lib/figures/export-layout';

type Json = any;

export type TexBuildInput = {
  doc: Json;
  refs: Ref[];
  title?: string;
  abstractText?: string;
  keywords?: string[];
  style: StyleId;
  language?: 'tr' | 'en';
  bibliographyTitle?: string;
  figureCaptionPlacement?: FigureCaptionPlacement;
};

export type TexAsset = {
  filename: string;
  base64: string;
};

export type TexBuildOutput = {
  tex: string;
  bib: string;
  bibFilename: string;
  assets: TexAsset[];
  warnings: string[];
};

type BibliographyConfig = {
  biblatexStyle: string;
  sorting: string;
  maxBibNames?: number;
  minBibNames?: number;
};

const STYLE_PACKAGE: Record<CitationStyle, BibliographyConfig> = {
  // Use styles bundled with core biblatex for broad TeX Live/MiKTeX
  // compatibility. Journal-specific punctuation still needs final review.
  vancouver: { biblatexStyle: 'numeric-comp', sorting: 'none' },
  'sage-vancouver': {
    biblatexStyle: 'numeric-comp',
    sorting: 'none',
    maxBibNames: 3,
    minBibNames: 3,
  },
  ama: { biblatexStyle: 'numeric-comp', sorting: 'none' },
  ieee: { biblatexStyle: 'numeric-comp', sorting: 'none' },
  apa: { biblatexStyle: 'authoryear', sorting: 'nyt' },
  'mdpi-acs': {
    biblatexStyle: 'numeric-comp',
    sorting: 'none',
    maxBibNames: 10,
    minBibNames: 10,
  },
  'mdpi-chicago': {
    biblatexStyle: 'authoryear',
    sorting: 'nyt',
    maxBibNames: 10,
    minBibNames: 10,
  },
  'mdpi-apa': { biblatexStyle: 'apa', sorting: 'nyt' },
};

export function buildLatex(input: TexBuildInput): TexBuildOutput {
  const bibFilename = 'refs.bib';
  const keyMap = buildCitationKeyMap(input.refs);
  const bib = generateBibtex(input.refs);
  const bibliography = bibliographyConfig(input.style);
  const figureCaptionPlacement = input.figureCaptionPlacement ?? 'inline';
  const renderer = new LatexRenderer(input.doc, keyMap, input.style, figureCaptionPlacement);
  if (
    input.style === 'ama'
    || input.style === 'ieee'
    || input.style === 'vancouver'
    || input.style === 'sage-vancouver'
    || input.style === 'mdpi-acs'
  ) {
    renderer.addExportWarning(
      `The ${input.style.toUpperCase()} export uses biblatex's portable numeric-comp style; verify journal-specific bibliography punctuation.`,
    );
  } else if (input.style === 'mdpi-apa') {
    renderer.addExportWarning(
      'The MDPI-APA export uses biblatex-apa; verify the final bibliography with the target journal template.',
    );
  } else if (input.style === 'apa' || input.style === 'mdpi-chicago') {
    renderer.addExportWarning(
      `The ${input.style.toUpperCase()} export uses biblatex's portable authoryear style; verify journal-specific bibliography punctuation.`,
    );
  } else {
    renderer.addExportWarning(
      'The custom citation style was mapped to a portable biblatex style; verify the bibliography before submission.',
    );
  }
  const body = renderer.render();
  const tex = buildTexSource({
    title: input.title ?? 'Untitled',
    body,
    bibliography,
    bibFilename: 'refs',
    language: input.language ?? 'en',
    bibliographyTitle: input.bibliographyTitle ?? 'References',
    abstractText: input.abstractText,
    keywords: input.keywords,
    figureLegends: figureCaptionPlacement === 'after-bibliography'
      ? renderer.renderFigureLegends()
      : '',
    exportDate: new Date().toISOString(),
  });

  return {
    tex,
    bib,
    bibFilename,
    assets: renderer.assets,
    warnings: renderer.warnings,
  };
}

function bibliographyConfig(style: StyleId): BibliographyConfig {
  const builtin = STYLE_PACKAGE[style as CitationStyle];
  if (builtin) return builtin;
  return isNumericStyle(style)
    ? { biblatexStyle: 'numeric-comp', sorting: 'none' }
    : { biblatexStyle: 'authoryear', sorting: 'nyt' };
}

function buildTexSource(o: {
  title: string;
  body: string;
  bibliography: BibliographyConfig;
  bibFilename: string;
  language: 'tr' | 'en';
  bibliographyTitle: string;
  abstractText?: string;
  keywords?: string[];
  figureLegends: string;
  exportDate: string;
}): string {
  const babelLanguages = o.language === 'tr' ? 'english,turkish' : 'turkish,english';
  const bibliographyNameOptions = [
    o.bibliography.maxBibNames != null
      ? `  maxbibnames=${o.bibliography.maxBibNames},`
      : '',
    o.bibliography.minBibNames != null
      ? `  minbibnames=${o.bibliography.minBibNames},`
      : '',
  ].filter(Boolean).join('\n');

  return `% !TEX TS-program = LuaLaTeX
% !TEX encoding = UTF-8 Unicode
% Generated by EndNoteRE
% Title: ${escapeTex(o.title)}
% Export date: ${o.exportDate}
\\documentclass[11pt,a4paper]{article}

\\usepackage{fontspec}
\\defaultfontfeatures{Ligatures=TeX}
\\setmainfont{Latin Modern Roman}
\\usepackage[${babelLanguages}]{babel}
\\usepackage[a4paper,margin=2.5cm]{geometry}
\\usepackage{microtype}
\\usepackage{csquotes}
\\usepackage{amsmath,amssymb}
\\usepackage{graphicx}
\\usepackage{booktabs}
\\usepackage{tabularx}
\\usepackage{array}
\\usepackage{ragged2e}
\\usepackage{float}
\\usepackage{xcolor}
\\usepackage{soul}
\\usepackage[normalem]{ulem}
\\usepackage[
  backend=biber,
  style=${o.bibliography.biblatexStyle},
  sorting=${o.bibliography.sorting},
${bibliographyNameOptions ? `${bibliographyNameOptions}\n` : ''}  maxcitenames=2,
  giveninits=true,
  doi=true,
  url=true
]{biblatex}
\\usepackage[hidelinks]{hyperref}
\\addbibresource{${o.bibFilename}.bib}

\\setlength{\\parindent}{1.25cm}
\\setlength{\\parskip}{0pt}
\\renewcommand{\\arraystretch}{1.15}

\\title{${escapeTex(o.title)}}
\\author{}
\\date{}

\\begin{document}
\\maketitle

${renderAbstractBlock(o.abstractText, o.keywords)}

${o.body}

\\clearpage
\\printbibliography[title={${escapeTex(o.bibliographyTitle)}}]

${o.figureLegends}

\\end{document}
`;
}

function renderAbstractBlock(abstractText?: string, keywords?: string[]): string {
  const text = abstractText?.trim();
  const cleanKeywords = normalizeKeywords(keywords);
  if (!text && cleanKeywords.length === 0) return '';
  const paragraphs = text
    ? text
        .split(/\n{2,}/)
        .map((part) => escapeTex(part.trim()))
        .filter(Boolean)
        .join('\n\n')
    : '';
  const keywordLine = cleanKeywords.length > 0
    ? `\\noindent\\textbf{Keywords:} ${escapeTex(cleanKeywords.join('; '))}`
    : '';
  return `\\begin{abstract}
${[paragraphs, keywordLine].filter(Boolean).join('\n\n')}
\\end{abstract}`;
}

function normalizeKeywords(keywords: string[] | undefined): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const keyword of keywords ?? []) {
    const clean = keyword.trim().replace(/[;,]+$/g, '');
    if (!clean) continue;
    const key = clean.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(clean);
  }
  return out;
}

class LatexRenderer {
  readonly assets: TexAsset[] = [];
  readonly warnings: string[] = [];

  private readonly imageFiles = new Map<string, string>();
  private readonly figureLabels = new Map<string, { label: string; kind: 'figure' | 'table' }>();
  private readonly figureNodeLabels = new WeakMap<object, string>();
  private imageCounter = 0;

  constructor(
    private readonly doc: Json,
    private readonly keyMap: Map<string, string>,
    private readonly style: StyleId,
    private readonly figureCaptionPlacement: FigureCaptionPlacement,
  ) {
    this.collectFigureLabels(doc);
  }

  render(): string {
    const blocks = Array.isArray(this.doc?.content)
      ? this.doc.content.map((node: Json) => this.renderBlock(node)).filter(Boolean)
      : [];
    return blocks.join('\n').trim();
  }

  renderFigureLegends(): string {
    const legends = collectFigureLegends(this.doc);
    if (legends.length === 0) return '';
    const entries = legends.map((legend) => {
      const cleanCap = cleanCaptionPrefix(legend.caption);
      return `\\noindent\\textbf{Figure ${legend.number}.}`
        + `${cleanCap ? ` ${escapeTex(cleanCap)}` : ''}\\par`;
    });
    return `\\clearpage
\\section*{Figure Legends}

${entries.join('\n\n')}`;
  }

  private renderBlock(node: Json): string {
    if (!node) return '';

    switch (node.type) {
      case 'paragraph':
        return this.renderParagraph(node);
      case 'heading':
        return this.renderHeading(node);
      case 'bulletList':
        return this.renderList(node, 'itemize');
      case 'orderedList':
        return this.renderList(node, 'enumerate');
      case 'blockquote':
        return this.environment('quote', this.renderBlockChildren(node));
      case 'table':
        return this.renderTable(node);
      case 'equation':
        return this.renderEquation(node);
      case 'figure':
        return this.renderFigure(node);
      case 'image':
        return this.renderStandaloneImage(node);
      case 'horizontalRule':
        return '\\par\\noindent\\rule{\\linewidth}{0.4pt}\\par\n';
      case 'codeBlock':
        return this.renderCodeBlock(node);
      default:
        return this.renderBlockChildren(node);
    }
  }

  private renderParagraph(node: Json): string {
    const content = this.renderInlineChildren(node);
    if (!content) return '';

    switch (node.attrs?.textAlign) {
      case 'center':
        return this.environment('center', content);
      case 'right':
        return this.environment('flushright', content);
      case 'left':
        return this.environment('flushleft', content);
      case 'justify':
        return this.environment('justify', content);
      default:
        return `${content}\n`;
    }
  }

  private renderHeading(node: Json): string {
    const level = Math.min(Math.max(Number(node.attrs?.level ?? 1), 1), 3);
    const command = level === 1 ? 'section' : level === 2 ? 'subsection' : 'subsubsection';
    return `\\${command}{${this.renderInlineChildren(node)}}\n`;
  }

  private renderList(node: Json, environment: 'itemize' | 'enumerate'): string {
    const items: string[] = [];
    for (const item of node.content ?? []) {
      if (item.type !== 'listItem') continue;
      const rendered: string[] = [];
      let itemOpened = false;

      for (const child of item.content ?? []) {
        if (!itemOpened && child.type === 'paragraph') {
          rendered.push(`\\item ${this.renderInlineChildren(child)}`);
          itemOpened = true;
        } else {
          if (!itemOpened) {
            rendered.push('\\item');
            itemOpened = true;
          }
          rendered.push(this.renderBlock(child).trim());
        }
      }
      if (!itemOpened) rendered.push('\\item');
      items.push(rendered.filter(Boolean).join('\n'));
    }
    return `\\begin{${environment}}\n${items.join('\n')}\n\\end{${environment}}\n`;
  }

  private renderTable(node: Json): string {
    const title = cleanOptionalText(node.attrs?.title);
    const footnote = cleanOptionalText(node.attrs?.footnote);
    const rows: Json[] = (node.content ?? []).filter((row: Json) => row.type === 'tableRow');
    const columnCount = rows.reduce((max: number, row: Json) => {
      const count = (row.content ?? []).reduce(
        (sum: number, cell: Json) => sum + Math.max(Number(cell.attrs?.colspan ?? 1), 1),
        0,
      );
      return Math.max(max, count);
    }, 0);
    if (columnCount === 0) return '';

    const renderedRows: string[] = [];
    rows.forEach((row, rowIndex) => {
      const cells: string[] = [];
      let usedColumns = 0;
      for (const cell of row.content ?? []) {
        const colspan = Math.max(Number(cell.attrs?.colspan ?? 1), 1);
        const content = this.renderTableCell(cell);
        cells.push(colspan > 1 ? `\\multicolumn{${colspan}}{l}{${content}}` : content);
        usedColumns += colspan;
        if (Number(cell.attrs?.rowspan ?? 1) > 1) {
          this.addWarning('A table contains row-spanning cells; verify the exported LaTeX table manually.');
        }
      }
      while (usedColumns < columnCount) {
        cells.push('');
        usedColumns += 1;
      }
      renderedRows.push(`    ${cells.join(' & ')} \\\\`);
      const allHeaders = (row.content ?? []).length > 0
        && (row.content ?? []).every((cell: Json) => cell.type === 'tableHeader');
      if (rowIndex === 0 && allHeaders) renderedRows.push('    \\midrule');
    });

    const columnSpec = `@{}${Array(columnCount).fill('>{\\RaggedRight\\arraybackslash}X').join('')}@{}`;
    return `\\begin{table}[htbp]
  \\centering
  \\caption{${escapeTex(title ?? '')}}
  \\begin{tabularx}{\\linewidth}{${columnSpec}}
    \\toprule
${renderedRows.join('\n')}
    \\bottomrule
  \\end{tabularx}
${footnote ? `  \\par\\vspace{0.35em}\n  \\begin{minipage}{\\linewidth}\\footnotesize ${escapeTex(footnote)}\\end{minipage}\n` : ''}\\end{table}
`;
  }

  private renderTableCell(cell: Json): string {
    const parts: string[] = [];
    for (const child of cell.content ?? []) {
      if (child.type === 'paragraph' || child.type === 'heading') {
        parts.push(this.renderInlineChildren(child));
      } else {
        parts.push(this.renderBlock(child).trim());
      }
    }
    const content = parts.filter(Boolean).join(' \\newline ');
    return cell.type === 'tableHeader' ? `\\textbf{${content}}` : content;
  }

  private renderEquation(node: Json): string {
    const latex = typeof node.attrs?.latex === 'string' ? node.attrs.latex.trim() : '';
    if (!latex) return '';
    return `\\begin{equation*}
${latex}
\\end{equation*}
`;
  }

  private renderFigure(node: Json): string {
    const kind: 'figure' | 'table' = node.attrs?.kind === 'table' ? 'table' : 'figure';
    const figId = typeof node.attrs?.figId === 'string' ? node.attrs.figId : '';
    const caption = typeof node.attrs?.caption === 'string' ? node.attrs.caption : '';
    const src = typeof node.attrs?.src === 'string' ? node.attrs.src : '';
    const registered = this.registerImage(src, kind);
    const label = typeof node === 'object' && node !== null
      ? this.figureNodeLabels.get(node)
      : undefined;
    const body: string[] = ['  \\centering'];

    if (registered) {
      body.push(`  \\includegraphics[width=\\linewidth,height=0.75\\textheight,keepaspectratio]{${registered}}`);
    } else if (src) {
      body.push(`  ${this.externalImagePlaceholder(src)}`);
    }
    const moveFigureCaption = kind === 'figure'
      && this.figureCaptionPlacement === 'after-bibliography';
    const cleanCap = cleanCaptionPrefix(caption);
    if (cleanCap && !moveFigureCaption) body.push(`  \\caption{${escapeTex(cleanCap)}}`);
    else if (label) body.push(`  \\refstepcounter{${kind}}`);
    if (label) body.push(`  \\label{${label}}`);

    return `\\begin{${kind}}[htbp]
${body.join('\n')}
\\end{${kind}}
`;
  }

  private renderStandaloneImage(node: Json): string {
    const src = typeof node.attrs?.src === 'string' ? node.attrs.src : '';
    if (!src) return '';
    const registered = this.registerImage(src, 'image');
    if (!registered) return `${this.externalImagePlaceholder(src)}\n`;
    return `\\begin{figure}[htbp]
  \\centering
  \\includegraphics[width=\\linewidth,height=0.75\\textheight,keepaspectratio]{${registered}}
\\end{figure}
`;
  }

  private renderCodeBlock(node: Json): string {
    const text = (node.content ?? []).map((child: Json) => child.text ?? '').join('');
    if (!text) return '';
    return `\\begin{verbatim}
${text}
\\end{verbatim}
`;
  }

  private renderBlockChildren(node: Json): string {
    if (!Array.isArray(node.content)) return '';
    return node.content.map((child: Json) => this.renderBlock(child)).filter(Boolean).join('\n');
  }

  private renderInlineChildren(node: Json): string {
    if (!Array.isArray(node.content)) return '';
    return node.content.map((child: Json) => this.renderInline(child)).join('');
  }

  private renderInline(node: Json): string {
    if (!node) return '';
    if (node.type === 'text') return applyMarks(node.text ?? '', node.marks ?? []);
    if (node.type === 'citation') return this.renderCitation(node);
    if (node.type === 'figureRef') return this.renderFigureRef(node);
    if (node.type === 'hardBreak') return ' \\\\\n';
    if (node.type === 'image') {
      const filename = this.registerImage(node.attrs?.src ?? '', 'inline-image');
      return filename
        ? `\\includegraphics[height=1.2em,keepaspectratio]{${filename}}`
        : this.externalImagePlaceholder(node.attrs?.src ?? '');
    }
    if (Array.isArray(node.content)) {
      return node.content.map((child: Json) => this.renderInline(child)).join('');
    }
    return '';
  }

  private renderCitation(node: Json): string {
    const ids: string[] = Array.isArray(node.attrs?.refIds) ? node.attrs.refIds : [];
    const keys = ids.map((id) => this.keyMap.get(id)).filter((key): key is string => Boolean(key));
    if (keys.length === 0) {
      this.addWarning('A citation could not be matched to a bibliography entry.');
      return '\\textbf{[?]}';
    }

    const locator = cleanOptionalText(node.attrs?.locator);
    const prefix = cleanOptionalText(node.attrs?.prefix);
    const suffix = cleanOptionalText(node.attrs?.suffix);
    const suppressAuthor = Boolean(node.attrs?.suppressAuthor);
    let command: string;

    if (suppressAuthor && !isNumericStyle(this.style)) {
      command = citationCommand('citeyear', keys, locator);
      command = `\\mkbibparens{${command}}`;
    } else {
      command = citationCommand(
        this.style === 'sage-vancouver'
          ? 'supercite'
          : isNumericStyle(this.style)
            ? 'cite'
            : 'parencite',
        keys,
        locator,
      );
    }

    return `${prefix ? `${escapeTex(prefix)} ` : ''}${command}${suffix ? ` ${escapeTex(suffix)}` : ''}`;
  }

  private renderFigureRef(node: Json): string {
    const figId = typeof node.attrs?.figId === 'string' ? node.attrs.figId : '';
    const target = this.figureLabels.get(figId);
    if (!target) {
      this.addWarning(`A figure/table cross-reference has no matching target (${figId || 'missing id'}).`);
      return '\\textbf{[missing cross-reference]}';
    }
    const label = target.kind === 'table' ? 'Table' : 'Figure';
    return `${label}~\\ref{${target.label}}`;
  }

  private collectFigureLabels(node: Json): void {
    let figureNumber = 0;
    let tableNumber = 0;
    const used = new Set<string>();

    const walk = (current: Json): void => {
      if (!current) return;
      if (current.type === 'figure') {
        const kind: 'figure' | 'table' = current.attrs?.kind === 'table' ? 'table' : 'figure';
        const figId = typeof current.attrs?.figId === 'string' ? current.attrs.figId : '';
        if (kind === 'table') tableNumber += 1;
        else figureNumber += 1;
        if (figId) {
          const base = sanitizeLabel(figId) || `${kind}-${kind === 'table' ? tableNumber : figureNumber}`;
          let label = `${kind === 'table' ? 'tab' : 'fig'}:${base}`;
          let suffix = 2;
          while (used.has(label)) label = `${kind === 'table' ? 'tab' : 'fig'}:${base}-${suffix++}`;
          used.add(label);
          this.figureNodeLabels.set(current, label);
          if (this.figureLabels.has(figId)) {
            this.addWarning(`Duplicate figure/table id "${figId}" was exported with a unique label; cross-references target the first occurrence.`);
          } else {
            this.figureLabels.set(figId, { label, kind });
          }
        }
      }
      for (const child of current.content ?? []) walk(child);
    };
    walk(node);
  }

  private registerImage(src: string, prefix: string): string | null {
    if (!src) return null;
    const existing = this.imageFiles.get(src);
    if (existing) return existing;

    const match = src.match(/^data:image\/(png|jpe?g);base64,([A-Za-z0-9+/=\s]+)$/i);
    if (!match) {
      this.addWarning('An external or unsupported image was not embedded; verify its placeholder in the .tex file.');
      return null;
    }

    const extension = match[1].toLowerCase() === 'jpeg' ? 'jpg' : match[1].toLowerCase();
    const safePrefix = sanitizeFilename(prefix) || 'image';
    const filename = `assets/${safePrefix}-${++this.imageCounter}.${extension}`;
    this.assets.push({ filename, base64: match[2].replace(/\s+/g, '') });
    this.imageFiles.set(src, filename);
    return filename;
  }

  private externalImagePlaceholder(src: string): string {
    const safeUrl = sanitizeUrlForTex(src);
    if (!safeUrl) return '\\textbf{[image omitted]}';
    return `\\href{${safeUrl}}{\\textbf{[external image]}}`;
  }

  private environment(name: string, content: string): string {
    return `\\begin{${name}}
${content}
\\end{${name}}
`;
  }

  private addWarning(message: string): void {
    if (!this.warnings.includes(message)) this.warnings.push(message);
  }

  addExportWarning(message: string): void {
    this.addWarning(message);
  }
}

function citationCommand(
  command: 'cite' | 'parencite' | 'citeyear' | 'supercite',
  keys: string[],
  locator: string,
): string {
  const postnote = locator ? `[${escapeTex(locator)}]` : '';
  return `\\${command}${postnote}{${keys.join(',')}}`;
}

function applyMarks(text: string, marks: Array<{ type: string; attrs?: any }>): string {
  let rendered = escapeTex(text);
  for (const mark of marks) {
    switch (mark.type) {
      case 'bold':
        rendered = `\\textbf{${rendered}}`;
        break;
      case 'italic':
        rendered = `\\textit{${rendered}}`;
        break;
      case 'underline':
        rendered = `\\uline{${rendered}}`;
        break;
      case 'strike':
        rendered = `\\sout{${rendered}}`;
        break;
      case 'superscript':
        rendered = `\\textsuperscript{${rendered}}`;
        break;
      case 'subscript':
        rendered = `\\textsubscript{${rendered}}`;
        break;
      case 'code':
        rendered = `\\texttt{${rendered}}`;
        break;
      case 'highlight':
        rendered = `\\hl{${rendered}}`;
        break;
      case 'textStyle': {
        const color = String(mark.attrs?.color ?? '').replace('#', '');
        if (/^[0-9a-fA-F]{6}$/.test(color)) {
          rendered = `\\textcolor[HTML]{${color.toUpperCase()}}{${rendered}}`;
        }
        break;
      }
      case 'link': {
        const href = sanitizeUrlForTex(mark.attrs?.href ?? '');
        if (href) rendered = `\\href{${href}}{${rendered}}`;
        break;
      }
      default:
        break;
    }
  }
  return rendered;
}

function cleanOptionalText(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

function sanitizeLabel(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9:-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function sanitizeFilename(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function sanitizeUrlForTex(value: string): string {
  const cleaned = String(value)
    .replace(/[\r\n]/g, '')
    .replace(/\\/g, '/');
  try {
    return encodeURI(cleaned).replace(/([%#&_$])/g, '\\$1');
  } catch {
    return '';
  }
}

function escapeTex(value: string): string {
  return String(value)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/—/g, '---')
    .replace(/–/g, '--');
}

function cleanCaptionPrefix(caption: string): string {
  const trimmed = caption.trim();
  if (!trimmed) return '';
  // Match things like "Figure 1.", "Fig. 2:", "Table 12 -", "Tablo 3" etc.
  const regex = /^\s*(?:Figure|Fig|Resim|Res|Table|Tab|Tablo)\.?\s*\d+\s*[\.:\-—–\s]*/i;
  return trimmed.replace(regex, '').trim();
}
